### PR TITLE
do input conversion outside of GIL unlocking

### PR DESCRIPTION
**Pull request by hendrik-cliqz**
@uweschmitt 

The GIL unlocking support I did earlier only works if methods have no parameter. If they have it fails currently as it is not allowed to work with python objects after unlocking the GIL.

This fixes it for 1 type. If its ok I can enhance this for all other types.

### CODE REVIEW

**Comment by hroest** [comment]
@hendrik-cliqz could you provide a test for this case? that would be quite helpful

**Comment by hendrik-cliqz** [comment]
@hroest 

I started writing a test but I am currently to blind to see what is wrong with the code, I hope you might have seen this before:

    from cython.operator cimport dereference as deref, preincrement as inc, address as address
    from gil_testing cimport ClassUsingTheGil as _ClassUsingTheGil
    cdef extern from "autowrap_tools.hpp":
        char * _cast_const_away(char *) 

    cdef class ClassUsingTheGil:
    ^
    ------------------------------------------------------------

    gil_testing.pyx:16:5: 'ClassUsingTheGil' redeclared

**Comment by hendrik-cliqz** [comment]
got it working: Some problem with naming the files.

**Comment by hendrik-cliqz** [comment]
@hroest please have a look, now it is working.

**Comment by hroest** [comment]
great, this looks wonderful to me. 

However, I suggest to remove the file `tests/test_files/gil_testing_wrapper.pyx` from the pull request as this is the file that is automatically created during the test. Or is this file useful to compare the autowrap output with what is expected?

**Comment by hendrik-cliqz** [comment]
good point, I wondered myself and only put it in because the other tests have it.

**Comment by hroest** [comment]
maybe @uweschmitt can shed some light onto this but some of these files are probably also not checked in and only generated when the test is run?

apart from that, looks good to me

**Comment by uweschmitt** [comment]
I will have to check this, currently I'm at EP 2015 in spain.

**Comment by hendrik-cliqz** [comment]
@uweschmitt 

Can you take a look?

**Comment by hendrik-cliqz** [comment]
@uweschmitt 

Can I kindly ask you to have a look at this PR? The keyvi project (https://github.com/cliqz-oss/keyvi) has a dependency on this PR (only for development but still, would be nice to fix it).

**Comment by uweschmitt** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I'm on vacation and will have a look at your request next week.

Best
Uwe

Am 27. Oktober 2015 12:01:59 OEZ, schrieb Hendrik Muhs <notifications@github.com>:
>@uweschmitt
>
>Can I kindly ask you to have a look at this PR? The keyvi project
>(https://github.com/cliqz-oss/keyvi) has a dependency on this PR (only
>for development but still, would be nice to fix it).
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/uweschmitt/autowrap/pull/33#issuecomment-151440561

- --
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQFaBAEBCgBEBQJWL4nsPRxTY2htaXR0ICBVd2UgKElEIFNJUykgKG5vIHBhc3N3
b3JkKSA8dXdlLnNjaG1pdHRAaWQuZXRoei5jaD4ACgkQKI56IpXJmY2b3gf9H/pv
SrcxFjifWuQ479GD2mzTVqu5GURatmwhUBcsiV/omnswLTW3SBmzulE7tslmiSAx
Bt8no5aSfGaWXrUqh9lNjH3Gu4c/GME2evj4tTEuXlXgsXyAPFjBuqxRwTkkED/C
EK+sSsicR9IYKxIERtrznUfifSI6C9nx1FuXAVBcAmmA4fbBOu8MwYygil7S6zv9
ECcAr5Ia/6mN6Ks8lACK3dVvMsaCoMyawIs/UuwuCLLnD/l/c7HgEaalMV8iygRH
jbmsHihkEWZx+EcDRqkOPGlhDfhlgOIdUEVfdpEUnw1+XmqYhgLLgtR6smAbPF/I
FlHFa4YO/x4Ernvykw==
=DNEG
-----END PGP SIGNATURE-----

**Comment by uweschmitt** [comment]
@hendrik-cliqz : thanks for your contribution !

**Comment by hendrik-cliqz** [comment]
@uweschmitt Thanks for merging!

**Pull request merged**
